title: "Button Styles"
description: |
  Lots of different button styles, each for different reasons.

patterns:
  basic:
    title: "Buttons"
    description: |
      Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons beacus ethey should be the primary call-to-action for a screen.
    fields:
      - name: text
  ghost:
    description: |
      The ghost button should only be used on banners.
    width: 320
