title: "Navigations"
description: |
  This navigation should be placed on the products and details page.

patterns:
  secondary-nav:
    description: |
      This internal navigation is for users to be able to search/browse for fashionable items by the first letter of a celebrity music artist's name.
  names-nav:
    description: |
      Once the user chooses a letter, they must find the name of an artist in order to view the products/outfits in stock, worn by them.
  main-nav:
    description: |
      This navigation must be shown at the top of every page. It is the main navigation of the entire website.
