title: "Forms"
description: |
  Styles for the necessary fieldsets in a check out form. The background colour of the checkout page will be white.

patterns:
  text:
    description: |
      This style is used for inserting names and credit/debit card number. Required for submission.
  size:
    description: |
      This is a required fieldset used for choosing a desired size for the item you want to purchase.
  colours:
    description: |
      Required fieldset used for choosing a specific colour of desired item.
  payment:
    description: |
      This is a required field and only one can be chosen.
  text-area:
    description: |
      Optional field. Used for any clothing/outfit recommendations.
  submit-button:
    description: |
      Uses the basic button style.
  errors:
    description: |
      These styles show up if there are any errors/missing information in a form.
